version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo Instalar las dependencias de Python
      - pip3 install --upgrade pip
      - pip3 install pytest
      - pip3 install -r backend/requirements.txt
      - rm -rf dspt
      - mkdir backend/test-reports
  build:
    commands:
      - echo Ejecutar comando de pruebas pytest
      - cd backend
      - pytest
        --html=backend/test-reports/report.html
        -s
        -v
reports:
  coverage:
    files:
      - "backend/coverage/*"
    base-directory: 'backend/test-reports'
    discard-paths: yes
  report:
    files:
      - 'junit.xml'
      - 'report.html'
      - 'assets/*'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml