version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo Instalar las dependencias de Python
      - pip3 install --upgrade pip
      - pip3 install pytest
      - pip3 install -r backend/requirements.txt

  build:
    commands:
      - echo Ejecutar comando de pruebas pytest
      - cd backend
      - python -m pytest